# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={},
        ),
    ]
