# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carouselimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselImage',
            new_name='CarouselItem',
        ),
    ]
