# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181107_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
