# Generated by Django 2.1.3 on 2018-11-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181108_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
