# Generated by Django 2.2.6 on 2019-10-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=40)),
                ('title_en', models.CharField(max_length=40)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, default='book', max_length=20, null=True)),
                ('url', models.URLField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title_tr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('redirect_link', models.CharField(blank=True, default='', max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'ordering': ['site', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title_tr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('blank_page', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('answer_tr', models.TextField()),
                ('answer_en', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='_website.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site'),
        ),
        migrations.CreateModel(
            name='ContestRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ContestLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('subtitle_tr', models.CharField(blank=True, max_length=100)),
                ('subtitle_en', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=40)),
                ('title_en', models.CharField(max_length=40)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_website.Site')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
