# Generated by Django 2.1.5 on 2019-03-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=40)),
                ('title_en', models.CharField(max_length=40)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('subtitle_tr', models.CharField(blank=True, max_length=100)),
                ('subtitle_en', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContestFAQItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('answer_tr', models.TextField()),
                ('answer_en', models.TextField()),
            ],
            options={
                'abstract': False,
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ContestRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
            ],
            options={
                'abstract': False,
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ContestSupportedLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=40)),
                ('title_en', models.CharField(max_length=40)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='_website.Event')),
            ],
        ),
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=20)),
                ('title_tr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('blank_page', models.BooleanField(default=False)),
                ('enable_carousel', models.BooleanField(default=True)),
                ('add_to_menu', models.BooleanField(default=False)),
                ('item_place', models.CharField(choices=[('l', 'left'), ('r', 'right')], default='r', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_site_banner', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, default='book', max_length=20, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='main_image',
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_images', to='_website.Option')),
            ],
        ),
    ]
