# Generated by Django 2.1.7 on 2019-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='redirect_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
