# Generated by Django 2.2.6 on 2019-11-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0002_auto_20191114_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='display_name',
            field=models.CharField(default='METU CCLUB', max_length=100),
            preserve_default=False,
        ),
    ]
