# Generated by Django 2.1.7 on 2019-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0002_flatpage_redirect_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='redirect_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
