# Generated by Django 2.2.6 on 2019-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0003_site_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestlanguage',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
