# Generated by Django 2.1.7 on 2019-04-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0003_auto_20190320_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='contestsupportedlanguage',
            options={'ordering': ['name']},
        ),
    ]
