# Generated by Django 2.2.6 on 2019-11-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0004_auto_20191114_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
