# Generated by Django 2.2.4 on 2019-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0004_auto_20190430_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='item_place',
            field=models.CharField(choices=[('l', 'left'), ('r', 'right'), ('n', 'none')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='site',
            field=models.CharField(choices=[('main', 'main'), ('contest', 'contest')], max_length=20),
        ),
    ]
