# Generated by Django 2.2.9 on 2020-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0007_flatpage_home_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='redirect_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='redirect_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
