# Generated by Django 2.2.9 on 2020-01-29 18:30

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0008_auto_20200129_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='content_en',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='content_tr',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='title_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
