# Generated by Django 3.2.2 on 2021-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_website', '0009_auto_20200129_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestrule',
            options={'ordering': ['site', 'order', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['site', 'order', '-pk']},
        ),
        migrations.AddField(
            model_name='contestrule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
